### PR TITLE
change getEmitter/getReceiver for getDevice

### PR DESCRIPTION
**Pull request by KelvinYang0320**
When testing my repo [deepbots-panda](https://github.com/KelvinYang0320/deepbots-panda) on Webots R2021a, there are some deprecation warnings.
DEPRECATION: Robot.getEmitter is deprecated, please use Robot.getDevice instead.
I have changed these for <code> getDevice</code> in my local deepbots package to get rid of the warning message.

### CODE REVIEW

**Comment by tsampazk** [comment]
Thank you very much for your contribution!

I am currently testing the code and how it behaves in older Webots versions.

**Review by tsampazk — DISMISSED** [review]
Everything looks fine! 

`getDevice()` does not work properly in webots versions earlier than 2021, but we can warn users in the new changelog we are going to add in the new version. I think it's ok to break backwards compatibility because we are moving into a major release anyway.

**Comment by ManosMagnus** [comment]
Hello @KelvinYang0320, 

Because there are some updates in `aidudezzz/dev` branch, you branch should be rebased.

The command in your local branch should be something like
```git rebase aidudezzz/dev 
git push -f origin/dev``

Excuse us for the inconvenience. If you have any problem with rebasing, let me know

**Comment by KelvinYang0320** [comment]
@ManosMagnus I have run these command to rebase my branch, thank you!

> Hello @KelvinYang0320,
> 
> Because there are some updates in `aidudezzz/dev` branch, your branch should be rebased.
> 
> The command in your local branch should be something like
> 
> ```
> git remote add aidudezzz https://github.com/aidudezzz/deepbots.git
> git fetch aidudezzz
> git rebase aidudezzz/dev;
> git push -f origin/dev
> ```
> 
> Excuse us for the inconvenience. If you have any problem with rebasing, let me know

**Review by ManosMagnus — APPROVED** [review]

**Comment by ManosMagnus** [comment]
Thank you @KelvinYang0320! @tsampazk will add you at the contributors list

**Comment by tsampazk** [comment]
@all-contributors please add @KelvinYang0320 for code

**Comment by KelvinYang0320** [comment]
@ManosMagnus @tsampazk 
Thank you very much!

**Comment by tsampazk** [comment]
@all-contributors please add @KelvinYang0320 for code

**Comment by tsampazk** [comment]
@all-contributors please add @KelvinYang0320 for code

**Comment by tsampazk** [comment]
@all-contributors please add @KelvinYang0320 for code

**Comment by tsampazk** [comment]
@all-contributors please add @KelvinYang0320 for code

**Pull request merged**
